version: "3.8"

services:
    application:
        build:
            dockerfile: .docker/php/Dockerfile
            context: ./
            target: app_php_dev
            args:
              GIT_USER_EMAIL: ${GIT_USER_EMAIL}
              GIT_USER_NAME: ${GIT_USER_NAME}
        env_file:
            - .env
        volumes:
            - .:/app
