name: Psalm

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

jobs:
  psalm:
    runs-on: ubuntu-latest
    name: Psalm complete run
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Static analysis
        run: ./vendor/bin/psalm --config='./psalm.xml' --shepherd --stats --output-format=github --php-version='8.2'
